### ISSUE TITLE
dev: move pypi publish workflow to poetry

### ISSUE THREAD

**Issue by julianprester** [CoLRev-Ecosystem/colrev#137]
We're using `poetry` for package management and could move the GitHub action workflow for building and publishing also to poetry for consistency.

Sample code: https://www.digitalocean.com/community/tutorials/how-to-publish-python-packages-to-pypi-using-poetry-on-ubuntu-22-04

**Comment by geritwagner** [comment]
Can we close this issue or are there further changes related to GitHub actions and poetry?
